spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    # LAZY Loading 시 조건절에서 단건으로 조회 하지 않고 IN으로 조회하도록 설정
    properties:
      hibernate:
        default_batch_fetch_size: 100
  datasource:
    url: jdbc:mysql://${MYSQL_URL:localhost}:3306/order?character-set-server=utf8mb4
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:rootpassword}
    hikari:
      # 1. 최대 커넥션 수: 너무 크면 DB 부하 증가.
      maximum-pool-size: 10
      # 2. 최소 유휴 커넥션 수: max와 동일하게 설정하여 커넥션 생성/제거 비용 최소화
      minimum-idle: 10
      # 3. 커넥션 획득 대기 시간 (ms): 너무 길면 웹 서버 스레드 고갈
      connection-timeout: 30000 # 30초
      # 4. 커넥션 최대 생명 주기 (ms): DB 타임아웃보다 짧게 설정 (MySQL은 기본 8시간)
      max-lifetime: 1800000 # 30분